// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkVTYW6T5RC2zyqjr0sH_1oNjd8iMKPc',
    appId: '1:446764206648:web:f714359927b8ff4fab34cd',
    messagingSenderId: '446764206648',
    projectId: 'my-ecommerce-comics-app',
    authDomain: 'my-ecommerce-comics-app.firebaseapp.com',
    storageBucket: 'my-ecommerce-comics-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_loMjNeA3JI7AeQAC1SgDIQIoegQS3M',
    appId: '1:446764206648:android:b1b5c3853efde557ab34cd',
    messagingSenderId: '446764206648',
    projectId: 'my-ecommerce-comics-app',
    storageBucket: 'my-ecommerce-comics-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIKvTpPgCqKP64nbYGx5Ca0CRj9reunts',
    appId: '1:446764206648:ios:99e08356facb0972ab34cd',
    messagingSenderId: '446764206648',
    projectId: 'my-ecommerce-comics-app',
    storageBucket: 'my-ecommerce-comics-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIKvTpPgCqKP64nbYGx5Ca0CRj9reunts',
    appId: '1:446764206648:ios:99e08356facb0972ab34cd',
    messagingSenderId: '446764206648',
    projectId: 'my-ecommerce-comics-app',
    storageBucket: 'my-ecommerce-comics-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdkVTYW6T5RC2zyqjr0sH_1oNjd8iMKPc',
    appId: '1:446764206648:web:b432303c9766a5eeab34cd',
    messagingSenderId: '446764206648',
    projectId: 'my-ecommerce-comics-app',
    authDomain: 'my-ecommerce-comics-app.firebaseapp.com',
    storageBucket: 'my-ecommerce-comics-app.firebasestorage.app',
  );
}
